<?php


namespace app\enums;


class AccountId extends \MyCLabs\Enum\Enum
{
    const GROSS_SALES = 1;
    const TOTAL_DISCOUNTS_RETURNS = 2;
    const TOTAL_BAD_DEBT_WRITENOFF = 3;
    const TOTAL_SALES_TAX_DISCOUNTS_WRITEOFFS = 4;
    const NET_SALES = 5;
    const TOTAL_SALES_COMMISSION = 6;
    const TOTAL_DIRECT_LABOR = 7;
    const TOTAL_SUBCONTRACTORS = 8;
    const TOTAL_MATERIALS = 9;
    const TOTAL_EQUIPMENT = 10;
    const TOTAL_DIRECT_TRANSPORTATION = 11;
    const TOTAL_DIRECT_TRAVEL = 12;
    const UNIQUE_COGS_ITEM_B_TO_BUSINESS = 13;
    const TOTAL_OTHER_DIRECT_COSTS = 14;
    const COGS = 15;
    const GROSS_PROFIT = 16;
    const TOTAL_MARKETING_INVESTMENT = 17;
    const TOTAL_TRAVEL_AND_ENTERTAINMENT = 18;
    const TOTAL_OFFICE_EXPENSE = 19;
    const TOTAL_OFFICE_PAYROLL = 20;
    const TOTAL_INSURANCE = 21;
    const TOTAL_OUTSIDE_FEES = 22;
    const TOTAL_PROPERTY_EXPENSE = 23;
    const TOTAL_UTILIITIES = 24;
    const UNIQUE_SG_AND_A_ITEM_C_TO_BUSINESS = 25;
    const UNIQUE_SG_AND_A_ITEM_D_TO_BUSINESS = 26;
    const TOTAL_MISCELLANEOUS_EXPENSE = 27;
    const TOTAL_SG_AND_A_EXPENSE = 28;
    const OPERATING_INCOME = 29;
    const TOTAL_OTHER_INCOME = 30;
    const TOTAL_OTHER_EXPENSES = 31;
    const TOTAL_OWNERS_COMPENSATION = 32;
    const TOTAL_INTEREST = 33;
    const TOTAL_TAXES = 34;
    const TOTAL_DEP_AND_AMM_EXPENSE = 35;
    const TOTAL_NONOPERATING_EXPENSE_LESS_NONOPERATING_INCOME = 36;
    const NET_INCOME = 37;
}